#!/usr/bin/env python3

import requests as req
from sys import argv, stderr
import json
from os.path import expanduser

CACHEFILE=expanduser("~/.cache/aur2cpan-name.json")

headers={
	'User-Agent': 'CpanBot/1.0 '+req.utils.default_user_agent()
}

def prerr(str):
	print(str, file=stderr)
	exit(1)

def prdata(data, pr_lic):
	ln=data["name"]
	if pr_lic:
		ln+="\t"
		ln+=data["license"]
	print(ln)
	exit(0)

cache = {}
try:
	with open(CACHEFILE, "r") as f:
		cache = json.load(f)
except:
	pass

if len(argv)<=1:
	prerr("Usage: {0} <perl-pkg-name> [--print-license]".format(argv[0]))

pkg_name=argv[1]

print_lic=False
if len(argv)>2:
	print_lic=argv[1]=="--print-license"

if pkg_name in cache:
	if cache[pkg_name] is dict:
		prdata(cache[pkg_name], print_lic)

r=req.get("https://aur.archlinux.org/rpc/v5/info/"+pkg_name, headers=headers)
r.raise_for_status()
aurdata=r.json()

if aurdata["resultcount"]<1:
	prerr("No package named '{0}' found on AUR!".format(pkg_name))

cpan_url=aurdata["results"][0]["URL"]
cpan_url=cpan_url.split('/')
cpan_type="release"
cpan_url="https://fastapi.metacpan.org/v1/"+cpan_type+"/"+cpan_url[-1]

r=req.get(cpan_url, headers=headers)
r.raise_for_status()
cpandata=r.json()

cache[pkg_name]={"name": cpandata["main_module"]}

with open(CACHEFILE, "w") as f:
	json.dump(cache, f)

prdata(cache[pkg_name], print_lic)
