#!/usr/bin/env python3

# Mail handler for Postfix (or similar mailing daemons)
# Usage: add to /etc/postfix/aliases:
#   cpanbot: |/usr/bin/cpanbot-mail
# and also start cpanbot-daemon.service

import email
from re import match
from sys import stdin
e=email.message_from_file(stdin)
subj=e["Subject"]
m=match("AUR Out-of-date Notification for (.*)$", subj)

if m is not None:
	with open("/tmp/cpanbot.fifo", "w") as f:
		f.write(m[1])
		f.write('\n')
