#!/usr/bin/env python3

from sys import argv, stderr
from cpantools import *

def prerr(str):
	print(str, file=stderr)
	exit(1)

if len(argv)<=1:
	prerr("Usage: {0} <Pkg::Name> [--spdx]".format(argv[0]))

pkg_name=argv[1]

print_spdx=False
if len(argv)>2:
	print_spdx=argv[2]=="--spdx"

cpan_release, _=cpan_module_to_release(pkg_name)
cpandata=cpan_get_release_info(cpan_release)
cpanmeta=cpandata["metadata"]

if not print_spdx:
	print(xlate_lic(cpanmeta["license"]))
elif "x_spdx_expression" in cpanmeta:
	cache[pkg_name]["spdx"]=cpanmeta["x_spdx_expression"]
else:
	prerr("SPDX data not available!")
