#!/bin/bash
set -e

##########################################
# CPAN2AUR2Git bot (CpanBot)
# Usage: cpan2aur2git <Perl::Pkg::Name>
# Needs Git and SSH to be correctly
#   configured for AUR uploading
#
# (c) CsokiCraft, 2023
# SPDX-License-Identifier: GPL-3.0-or-later
##########################################

PERL_PKG="$1"

[ -z "$PERL_PKG" ] && {
	echo "Usage: cpan2aur2git <Perl::Pkg::Name> [--to-diff|--fixup]" >&1
	exit 1
}

TMPDIR="$(mktemp -d)"
trap 'cd && rm -rf "$TMPDIR"' EXIT
cd "$TMPDIR"

cpan2aur "$PERL_PKG"

TARFILE="$(ls -1b *.tar.gz | head -n1)"
AUR_PKG="$(tar tf "$TARFILE" | head -n1 | tr -d /)"

git clone "ssh://aur@aur.archlinux.org/$AUR_PKG"
tar xf "$TARFILE"

cd "$AUR_PKG"
sed -i "s/^# Contributor: .*$/# Contributor: CpanBot <cpanbot at sch bme hu>/" PKGBUILD

[ "x$CPANBOT_IGNORE_LICENSE" != "x1" ] && {
	LICENSE="$(aur2cpan-name "$AUR_PKG" --print-license)"
	sed -i "s/^license=(?:.*)$/license=($LICENSE)/" PKGBUILD
}

makepkg --printsrcinfo > .SRCINFO
git add PKGBUILD .SRCINFO && git commit -m "Converted '$PERL_PKG' with cpan2aur2git"

_op=push
[ "x$2" == "x--to-diff" ] && _op=show
[ "x$2" == "x--fixup" ]   && exit $(/bin/bash)
git $_op
